version: '3'

services:
  gerenciar-trello-frontend:
    image: gerenciar-trello-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
    container_name: gerenciar-trello-frontend
    restart: always
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - "./logs:/var/log/nginx"
    env_file:
      - .env
