version: '3.7'

services:
  trello-frontend:
    image: trello-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
    container_name: trello-frontend
    network_mode: bridge
    restart: always
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - "./logs:/var/log/nginx"
    env_file:
      - .env
