version: '3'

services:
  sonar-rotas-frontend:
    image: sonar-rotas-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
    container_name: sonar-rotas-frontend
    restart: always
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - "./logs:/var/log/nginx"
    env_file:
      - .env
